In [11]:
#TASK1
import numpy as np

print("\n=== PROBLEM 1 ===")

# 1
a = np.empty((2,2))
print("\n1. Empty array (2x2):")
print(a)

# 2
b = np.ones((4,2))
print("\n2. Ones array (4x2):")
print(b)

# 3
c = np.full((3,3), fill_value=7)
print("\n3. Full array of 7s:")
print(c)

# 4
given = np.array([[1,2,3],[4,5,6]])
d = np.zeros_like(given)
print("\n4. zeros_like(given):")
print(d)

# 5
e = np.ones_like(given)
print("\n5. ones_like(given):")
print(e)

# 6
new_list = [1,2,3,4]
f = np.array(new_list)
print("\n6. List → numpy array:")
print(f)




=== PROBLEM 1 ===

1. Empty array (2x2):
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array of 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like(given):
[[0 0 0]
 [0 0 0]]

5. ones_like(given):
[[1 1 1]
 [1 1 1]]

6. List → numpy array:
[1 2 3 4]


In [12]:
#TASK2
print("\n=== PROBLEM 2 ===")

# 1
p1 = np.arange(10, 50)
print("\n1. Array 10–49:")
print(p1)

# 2
p2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 matrix (0–8):")
print(p2)

# 3
p3 = np.eye(3)
print("\n3. Identity matrix:")
print(p3)

# 4
p4 = np.random.random(30)
print("\n4. Random array (30 values):")
print(p4)
print("Mean =", p4.mean())

# 5
p5 = np.random.random((10,10))
print("\n5. 10x10 random array:")
print(p5)
print("Min =", p5.min(), "Max =", p5.max())

# 6
p6 = np.zeros(10)
p6[4] = 1
print("\n6. Zero array with 5th element = 1:")
print(p6)

# 7
arr = np.array([1,2,0,0,4,0])
p7 = arr[::-1]
print("\n7. Reversed array:")
print(p7)

# 8
p8 = np.ones((6,6))
p8[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:")
print(p8)

# 9
p9 = np.zeros((8,8))
p9[1::2, ::2] = 1
p9[::2, 1::2] = 1
print("\n9. Checkerboard pattern:")
print(p9)



=== PROBLEM 2 ===

1. Array 10–49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0–8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (30 values):
[0.69370597 0.30305459 0.97816232 0.5769634  0.87939519 0.90687679
 0.85772474 0.64572039 0.96627405 0.2149061  0.86406489 0.2313876
 0.55513566 0.03627005 0.7236331  0.99687697 0.82576537 0.59691633
 0.10775849 0.41874472 0.15620944 0.4260663  0.10866066 0.64413032
 0.61184751 0.15867421 0.0139346  0.87578334 0.40593736 0.44385749]
Mean = 0.5408145990645703

5. 10x10 random array:
[[0.23877941 0.75303259 0.97179257 0.20032348 0.29418534 0.49502726
  0.86476615 0.29789874 0.99883518 0.09356937]
 [0.89914799 0.94148898 0.17598652 0.64701531 0.47990288 0.17205285
  0.29295346 0.65159443 0.46820834 0.62973093]
 [0.10845981 0.33558804 0.11761117 0.42334048 0.23402899 0.52149524
  0.32140924 0.39850

In [13]:
#TASK3
print("\n=== PROBLEM 3 ===")

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1
print("\n1. x + y:")
print(x + y)

# 2
print("\n2. x - y:")
print(x - y)

# 3
print("\n3. x * 3:")
print(x * 3)

# 4
print("\n4. Square of x:")
print(x**2)

# 5
print("\n5. Dot products:")
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =\n", np.dot(x,y))

# 6
print("\n6. Concatenate x & y (row-wise):")
print(np.concatenate((x,y), axis=0))

print("\nConcatenate v & w (column-wise):")
print(np.vstack((v,w)))

# 7
print("\n7. Why x & v fails:")
print("Error: x is 2D but v is 1D → shapes don’t match.")




=== PROBLEM 3 ===

1. x + y:
[[ 6  8]
 [10 13]]

2. x - y:
[[-4 -4]
 [-4 -3]]

3. x * 3:
[[ 3  6]
 [ 9 15]]

4. Square of x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v·w = 219
x·v = [29 77]
x·y =
 [[19 22]
 [50 58]]

6. Concatenate x & y (row-wise):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w (column-wise):
[[ 9 10]
 [11 12]]

7. Why x & v fails:
Error: x is 2D but v is 1D → shapes don’t match.


In [14]:
#TASK4
print("\n=== PROBLEM 4 ===")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1
A_inv = np.linalg.inv(A)
print("\n1. A × A⁻¹ = Identity:")
print(A.dot(A_inv))

# 2
AB = A.dot(B)
BA = B.dot(A)
print("\n2. AB:")
print(AB)
print("\nBA:")
print(BA)
print("\nAB != BA confirmed")

# 3
print("\n3. (AB)^T == B^T × A^T:")
print("LHS:\n", AB.T)
print("RHS:\n", B.T.dot(A.T))

# Solving system of equations
A_sys = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B_sys = np.array([-1, -3, 9])

solution = np.linalg.inv(A_sys).dot(B_sys)
print("\nSolution to system [x, y, z]:")
print(solution)



=== PROBLEM 4 ===

1. A × A⁻¹ = Identity:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB != BA confirmed

3. (AB)^T == B^T × A^T:
LHS:
 [[23 51]
 [13 29]]
RHS:
 [[23 51]
 [13 29]]

Solution to system [x, y, z]:
[ 2.  1. -2.]
