In [1]:
import numpy as np

In [2]:
l=[]
type(l)

list

In [7]:
np.array([1,2,3]).ndim

1

In [8]:
np.array([[1,2,3], [2,2,2]])

array([[1, 2, 3],
       [2, 2, 2]])

In [9]:
np.array([[1,2,3], [2,2,2]]).shape

(2, 3)

In [11]:
np.array([[[1,2,3], [2,2,2]]]).ndim

3

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((5,5),dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
for i in range(10):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [23]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.random.random(5)

array([0.50601291, 0.29419747, 0.138014  , 0.62512344, 0.92441641])

In [34]:
np.random.randint(10,size=(5,5))

array([[5, 3, 4, 2, 1],
       [0, 6, 0, 8, 1],
       [9, 9, 7, 5, 2],
       [1, 6, 0, 9, 5],
       [0, 5, 8, 5, 8]], dtype=int32)

In [36]:
a= np.ones((5,5))
b= np.ones((5,5))

print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [38]:
np.sin((a))

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [5]:
import numpy as np

random_array = np.random.random(30)

array_mean = random_array.mean()

print("Random array:")
print(random_array)
print("\nMean of the array:", array_mean)

Random array:
[0.70276388 0.18704314 0.77590356 0.2375367  0.34029279 0.78554117
 0.34751652 0.68447544 0.54605961 0.98676277 0.98558075 0.58987841
 0.57276007 0.69625486 0.10916777 0.20900652 0.13353062 0.15656695
 0.95652096 0.97843896 0.38024157 0.89121701 0.47823859 0.42978151
 0.54183018 0.86327524 0.79416427 0.67228793 0.57881922 0.65755708]

Mean of the array: 0.5756338022775126


In [44]:
a.max(axis=1)

array([94, 70, 81, 86, 83, 56], dtype=int32)

In [6]:
a = np.array([[1,2],[2,5]])
np.linalg.eig(a)

EigResult(eigenvalues=array([0.17157288, 5.82842712]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

In [9]:

arr = np.array([1, 2, 0, 0, 4, 0])
rev = np.flip(arr)

print(rev)


[0 4 0 0 2 1]


In [10]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [13]:
print("Add the two arrays:")
print(x + y)

Add the two arrays:
[[ 6  8]
 [10 13]]


In [14]:
print("Subtract the two arrays:")
print(x - y)


Subtract the two arrays:
[[-4 -4]
 [-4 -3]]


In [15]:
print("Multiply array with integer 3:")
print(x * 3)

Multiply array with integer 3:
[[ 3  6]
 [ 9 15]]


In [16]:
print("Square of each element:")
print(x ** 2)

Square of each element:
[[ 1  4]
 [ 9 25]]


In [17]:
print("Dot product v and w:")
print(np.dot(v, w))

Dot product v and w:
219


In [18]:
print("Dot product x and v:")
print(np.dot(x, v))

Dot product x and v:
[29 77]


In [19]:
print("Dot product x and y:")
print(np.dot(x, y))

Dot product x and y:
[[19 22]
 [50 58]]


In [20]:
print("Concatenate x and y along row:")
print(np.concatenate((x, y), axis=0))

Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [21]:
print("Concatenate v and w along column:")
print(np.column_stack((v, w)))


Concatenate v and w along column:
[[ 9 11]
 [10 12]]


In [22]:
print("Concatenate x and v:")
try:
    result = np.concatenate((x, v))
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [23]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [24]:
print("A.A−1 = I:")
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print(identity_check)

A.A−1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [25]:
print("AB ≠ BA:")
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Are they equal?", np.array_equal(AB, BA))

AB ≠ BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are they equal? False


In [26]:
print("(AB)T = BT AT:")
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)T:")
print(AB_T)
print("BT AT:")
print(BT_AT)
print("Are they equal?", np.array_equal(AB_T, BT_AT))

(AB)T = BT AT:
(AB)T:
[[23 51]
 [13 29]]
BT AT:
[[23 51]
 [13 29]]
Are they equal? True


In [27]:
print("Solve system of linear equations:")
coefficients = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

inv_coefficients = np.linalg.inv(coefficients)
solution = np.dot(inv_coefficients, constants)
print(solution)

Solve system of linear equations:
[ 2.  1. -2.]


In [28]:
import time
import numpy as np

size = 1000000

In [29]:
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
list_time = time.time() - start_time
print(f"Python list time: {list_time:.6f} seconds")

Python list time: 0.219670 seconds


In [30]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start_time
print(f"NumPy array time: {numpy_time:.6f} seconds")

NumPy array time: 0.005662 seconds


In [31]:

list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
list_time = time.time() - start_time
print(f"Python list multiplication time: {list_time:.6f} seconds")

Python list multiplication time: 0.206783 seconds


In [32]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
result_arr = arr1 * arr2
numpy_time = time.time() - start_time
print(f"NumPy array multiplication time: {numpy_time:.6f} seconds")

NumPy array multiplication time: 0.004070 seconds


In [33]:
start_time = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
list_time = time.time() - start_time
print(f"Python list dot product time: {list_time:.6f} seconds")

Python list dot product time: 0.224011 seconds
