In [ ]:
import pandas as pd
import numpy as np


In [6]:
df = pd.read_csv('/content/student.csv')
df.head()

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [7]:
df.tail()


Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

In [8]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [9]:
df.describe()


Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [10]:
X = df[['Math', 'Reading']].values   # Features
Y = df['Writing'].values             # Target

print(X)
print(Y)

[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]
[ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94  75  68  71  85  46  58  46  84  58  57  59  77  63  68  99
  48  91  57  80  46  75  59  87  82  79  66  68  66  61  66  63

In [11]:
print(X)
print(Y)

[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]
[ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94  75  68  71  85  46  58  46  84  58  57  59  77  63  68  99
  48  91  57  80  46  75  59  87  82  79  66  68  66  61  66  63

In [12]:
np.random.seed(42)

indices = np.arange(len(X))
np.random.shuffle(indices)

split = int(0.8 * len(X))

train_idx = indices[:split]
test_idx = indices[split:]

X_train = X[train_idx]
X_test  = X[test_idx]

Y_train = Y[train_idx]
Y_test  = Y[test_idx]

print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[63 69]
 [42 37]
 [69 62]
 ...
 [50 58]
 [63 70]
 [64 73]]
[[ 72  77]
 [ 59  67]
 [ 59  56]
 [ 93  82]
 [ 69  64]
 [ 57  72]
 [ 59  65]
 [ 71  73]
 [ 42  53]
 [ 47  61]
 [ 68  59]
 [ 53  59]
 [ 84  98]
 [ 68  58]
 [ 78  80]
 [ 50  52]
 [ 52  71]
 [ 69  91]
 [ 54  70]
 [ 51  40]
 [ 65  75]
 [ 80  84]
 [ 69  76]
 [100 100]
 [ 60  63]
 [ 56  69]
 [ 48  46]
 [ 63  59]
 [ 47  45]
 [ 80  81]
 [ 61  76]
 [ 68  68]
 [ 82  78]
 [ 73  94]
 [ 59  64]
 [ 49  52]
 [ 91  97]
 [ 59  67]
 [ 68  74]
 [ 64  77]
 [ 93  76]
 [ 52  61]
 [ 56  73]
 [ 84 100]
 [ 79  81]
 [ 59  65]
 [ 72  73]
 [ 69  75]
 [ 61  59]
 [ 64  74]
 [ 64  74]
 [ 73  72]
 [ 96  86]
 [ 89  88]
 [ 61  55]
 [ 56  75]
 [ 61  63]
 [ 44  55]
 [ 80  71]
 [ 78  74]
 [ 78  83]
 [ 39  58]
 [ 90  96]
 [ 77  79]
 [ 60  76]
 [ 67  51]
 [ 56  51]
 [ 77  90]
 [100  98]
 [ 83  75]
 [ 65  80]
 [ 87  67]
 [ 80  81]
 [ 78  82]
 [ 56  65]
 [ 77  70]
 [ 62  43]
 [ 74  77]
 [ 61  70]
 [ 74  90]
 [ 73  87]
 [ 62  58]
 [ 95  84]
 [ 61  87]
 [ 61  77]
 [ 40

In [13]:
def cost_function(X, Y, W):
    n = len(Y)
    Y_pred = np.dot(X, W)
    cost = (1 / (2 * n)) * np.sum((Y_pred - Y) ** 2)
    return cost

In [14]:
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

cost = cost_function(X_test, Y_test, W_test)

if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong")

Proceed Further


In [15]:
def gradient_descent(X, Y, W, alpha, iterations):

    m = len(Y)
    cost_history = []

    for _ in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1 / m) * np.dot(X.T, loss)
        W = W - alpha * dw
        cost = cost_function(X, Y, W)
        cost_history.append(cost)

    return W, cost_history

In [16]:
np.random.seed(0)

X = np.random.rand(100, 3)
Y = np.random.rand(100)
W = np.random.rand(3)

alpha = 0.01
iterations = 1000

final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)

print("Final Parameters:", final_params)
print("Final Cost:", cost_history[-1])

Final Parameters: [0.20551667 0.54295081 0.10388027]
Final Cost: 0.05435492255484332


In [17]:
def rmse(Y, Y_pred):
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

In [18]:
def r2(Y, Y_pred):
    mean_y = np.mean(Y)
    ss_tot = np.sum((Y - mean_y) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    return 1 - (ss_res / ss_tot)

In [20]:
def main():

    data = pd.read_csv('/content/student.csv')

    X = data[['Math', 'Reading']].values
    Y = data['Writing'].values

    np.random.seed(42)
    indices = np.arange(len(X))
    np.random.shuffle(indices)
    split = int(0.8 * len(X))

    X_train = X[indices[:split]]
    X_test  = X[indices[split:]]
    Y_train = Y[indices[:split]]
    Y_test  = Y[indices[split:]]

    W = np.zeros(X_train.shape[1])
    alpha = 0.00001
    iterations = 1000

    W_opt, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    Y_pred = np.dot(X_test, W_opt)

    print("Final Weights:", W_opt)
    print("RMSE:", rmse(Y_test, Y_pred))
    print("R2 Score:", r2(Y_test, Y_pred))


if __name__ == "__main__":
    main()

Final Weights: [0.3533225  0.64122757]
RMSE: 5.258385317376058
R2 Score: 0.8688492410749991


In [22]:
#With an average prediction error of about 5 marks, my linear regression
#model was able to explain approximately 87% of the variation in writing
#scores, with R² = 0.8688 and RMSE = 5.25. This suggests that the
#predictive performance is good. As a result, my model performs
#satisfactorily and is neither overfitting nor underfitting.

#The model converged more quickly when I increased the learning rate,
#but if I increased it too much, the training became unstable and
#accuracy dropped.


#The model learned more smoothly but very slowly when I lowered the
#learning rate, necessitating more iterations.